version: 5.0.{build}
image: Visual Studio 2022
configuration: Release
build_script:
- ps: dotnet --version
- ps: dotnet build -c Release
test_script:
- ps: pushd nClam.Tests; dotnet test -c Release --verbosity normal; popd
artifacts:
- path: nClam\bin\Release\*.nupkg